### ISSUE TITLE
Publish it as "gitbook-completions"

### ISSUE THREAD

**Issue by SamyPesse** [mklabs/gitbook-completions#1]
Awesome work 👍

Why not publishing it as `gitbook-completions` instead of `mklabs/gitbook-completions` ?

I don't know much about tab completions, is it something that we can easily add to `gitbook-cli` itself (without requiring changing the shell config files) ?

**Comment by mklabs** [comment]
Glad to know it is something you'd like to be interested in :+1: 

I plan to work a bit more on it this week-end and next week, to have slightly more smart completions (like d1769ab4f4a933d6cc3e18a6bdc1e69cea46093e) Once more fleshed out, I plan to release it on the registry.

We can definitely add it to gitbook-cli itself but shell config files must be updated to in order to hook into SHELL completion system, that's something we can't bypass.

That being said, there is also a way to enable it without changing shell config files but it's up to the user to launch a command (like `. <(tabtab install --stdout --name gitbook)` [docs](https://github.com/mklabs/node-tabtab#manual-installation)). The downside is that it only enables it for the current shell.

**Comment by mklabs** [comment]
@SamyPesse Done, just published as gitbook-completions: https://www.npmjs.com/package/gitbook-completions
